Added GetScore
PepijnF/ProftaakRockstars-Backend pull request #36
Opened 2021-11-18 13:17 UTC by ebekoudijs

2021-11-18 13:25 UTC, PepijnF requested changes

2021-11-18 13:25 UTC, PepijnF commented on WebSockies/Controllers/QuizController.cs
> +                user.SocketConnection.Send(JsonSerializer.Serialize(new ResponseModel("SplashScreen","OK", userList.ToString())));
Dit returned geen json lijst

2021-11-18 13:37 UTC, ebekoudijs commented on WebSockies/Controllers/QuizController.cs
> +                user.SocketConnection.Send(JsonSerializer.Serialize(new ResponseModel("SplashScreen","OK", userList.ToString())));
Oei, dat is niet best

2021-11-18 13:56 UTC, PepijnF commented
Resolves #29

2021-11-25 13:03 UTC, ebekoudijs commented
@PepijnF

2021-11-25 13:36 UTC, merged